language: python
python:
- '3.6.4'

branches:
  only:
    - master

addons:
  apt:
    packages:
      unzip
      make

before_install:
- wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip
- unzip packer_1.4.4_linux_amd64.zip -d packer
- sudo mv packer/packer /usr/local/bin/
- wget https://releases.hashicorp.com/terraform/0.12.11/terraform_0.12.11_linux_amd64.zip
- unzip terraform_0.12.11_linux_amd64.zip -d terraform
- sudo mv terraform/terraform /usr/local/bin/
- touch .env

script:
- flake8 .

deploy:
  # create an image when tagged
  - provider: script
    # preserve patch to packer configuration by skipping cleanup
    skip_cleanup: true
    script: make packer-build

